language: node_js
node_js:
  - 12

branches:
  only:
    - main

before_install:
  - npm i -g npm@latest
  - npm i

before_script:
  - npm install -g @angular/cli

cache:
  directories:
    - ./node_modules

script:
  - ng build
  - ng test
